
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;
import java.util.Map;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dodo
 */
public class Assign2 extends javax.swing.JFrame {

    /**
     * Creates new form Assign2
     */
    public Assign2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        URL1 = new javax.swing.JTextField();
        URL2 = new javax.swing.JTextField();
        GetPage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showURL1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        showURL2 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Header = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Thread = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tanapat Nantakitwattanachot s5050319@kmitl.ac.th - Java Web Browser (Network Programming Class Assignment)");

        jLabel1.setText("URL1");

        jLabel2.setText("URL2");

        GetPage.setText("GO");
        GetPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPageActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(showURL1);

        jScrollPane2.setViewportView(showURL2);

        jScrollPane3.setViewportView(Header);

        jScrollPane4.setViewportView(Thread);

        jLabel3.setText("Header");

        jLabel4.setText("Thread");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(URL1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(URL2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154)
                        .addComponent(GetPage)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GetPage)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(URL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(URL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void GetPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPageActionPerformed
        //Thread.setText(Thread.getText());
        MyThread link1 = new MyThread(URL1.getText(), "Thread1");
        MyThread link2 = new MyThread(URL2.getText(), "Thread2");
        link1.start();
        link2.start();
    }
/*
    public void Url1() {
        try {
            Thread.setText(Thread.getText() + "Thead1 : Start Get URL\n");
            showURL1.setPage(URL1.getText());
            Thread.setText(Thread.getText() + "Thead1 : GetPage\n");

            Thread.setText(Thread.getText() + "Thread1 : Print Header\n");

            ShowHeader(URL1.getText(), "Thread1 :");
            Thread.setText(Thread.getText() + "Thead1 : Finish\n");
        } catch (IOException ex) {
            //Logger.getLogger(Assign2.class.getName()).log(Level.SEVERE, null, ex);
            printf("not have URL1");
        }
    }//GEN-LAST:event_GetPageActionPerformed
*/
    public void ShowHeader(String URL, String Thread) {
        String url = URL;
        String thread = Thread;
        try {

            URL obj = new URL(url);
            URLConnection conn = obj.openConnection();
            Map<String, List<String>> map = conn.getHeaderFields();
            Header.setText(Header.getText() + thread + " :\n");

            for (Map.Entry<String, List<String>> entry : map.entrySet()) {
                Header.setText(Header.getText() + "Key : " + entry.getKey() + " ,Value : " + entry.getValue() + "\n");
            }
            Header.setText(Header.getText() + "\nGet HTTP Header For : " + thread + "\n");
            String server = conn.getHeaderField("Server");

            if (server == null) {
                Header.setText(Header.getText() + "'Server' is not found!\n");
            } else {
                Header.setText(Header.getText() + "Server : " + server + "\n");
            }
            Header.setText(Header.getText() + "Done\n________________________\n");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public class MyThread extends Thread {

        String link, thrNo;
        int delay = 5000;

        public MyThread(String url, String no) {
            link = url;
            thrNo = no;
        }
        @Override
        public void run() {

            try {
                Thread.setText(Thread.getText() + thrNo + " : Start Get URL\n");

                if (thrNo.equals("Thread1")) {
                    showURL1.setPage(link);

                }
                if (thrNo.equals("Thread2")) {
                    showURL2.setPage(link);

                }

                Thread.setText(Thread.getText() + thrNo + " : GetPage\n");

                Thread.setText(Thread.getText() + thrNo + " : Print Header\n");

                ShowHeader(link, thrNo);

                Thread.setText(Thread.getText() + thrNo + " : Finish\n");
            } catch (IOException ex) {
                //Logger.getLogger(Assign2.class.getName()).log(Level.SEVERE, null, ex);
                printf("cannot show");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetPage;
    private javax.swing.JEditorPane Header;
    private javax.swing.JEditorPane Thread;
    private javax.swing.JTextField URL1;
    private javax.swing.JTextField URL2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JEditorPane showURL1;
    private javax.swing.JEditorPane showURL2;
    // End of variables declaration//GEN-END:variables

    private void printf(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
